name: "login / build / push to dockerhub"

inputs:
  docker-username:
    description: "docker hub username"
    required: true
  docker-password:
    description: "docker hub password"
    required: true
  ruby-version:
    description: "Ruby Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ inputs.docker-username }}
        DOCKER_PASSWORD: ${{ inputs.docker-password }}
    - name: Build ${{ inputs.ruby-version }}
      shell: bash
      run: docker build -t masoo/ubuntu-2204-ruby:${{ inputs.ruby-version }} --build-arg ${{ inputs.ruby-version }} .
    - name: Push to docker hub :${{ inputs.ruby-version }}
      uses: actions-hub/docker@master
      with:
        args: push masoo/ubuntu-2204-ruby:${{ inputs.ruby-version }}
