name: "login / build / push to dockerhub"

inputs:
  docker-username:
    description: "docker hub username"
    required: true
  docker-password:
    description: "docker hub password"
    required: true
  ruby-version:
    description: "Ruby Version"
    required: true
  enable-cache-to:
    description: "Enable cache-to for registry cache"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: Build and push Ruby ${{ inputs.ruby-version }} (with cache-to)
      if: ${{ inputs.enable-cache-to == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: masoo/ubuntu-2204-ruby:${{ inputs.ruby-version }}
        build-args: |
          RUBY_VERSION=${{ inputs.ruby-version }}
          CACHE_BUST=$(date +%Y-%W)
        cache-from: type=registry,ref=masoo/ubuntu-2204-ruby:buildcache
        cache-to: type=registry,ref=masoo/ubuntu-2204-ruby:buildcache,mode=max
    - name: Build and push Ruby ${{ inputs.ruby-version }} (without cache-to)
      if: ${{ inputs.enable-cache-to != 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: masoo/ubuntu-2204-ruby:${{ inputs.ruby-version }}
        build-args: |
          RUBY_VERSION=${{ inputs.ruby-version }}
          CACHE_BUST=$(date +%Y-%W)
        cache-from: type=registry,ref=masoo/ubuntu-2204-ruby:buildcache
